import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        background: '#fcf8fa',
        'on-tertiary': '#ffffff',
        'surface-tint': '#565e74',
        'surface-container-high': '#eae7e9',
        'on-surface-variant': '#45464d',
        'on-secondary-container': '#006f66',
        'inverse-surface': '#303032',
        'tertiary-fixed': '#d3e4fe',
        'on-primary-container': '#7c839b',
        'on-tertiary-fixed': '#0b1c30',
        'on-secondary-fixed': '#00201d',
        primary: '#000000',
        'primary-container': '#131b2e',
        'on-surface': '#1b1b1d',
        'on-secondary': '#ffffff',
        'surface-dim': '#dcd9db',
        'tertiary-container': '#0b1c30',
        'on-primary-fixed-variant': '#3f465c',
        'tertiary-fixed-dim': '#b7c8e1',
        'on-error': '#ffffff',
        'primary-fixed': '#dae2fd',
        'secondary-container': '#86f2e4',
        'on-tertiary-fixed-variant': '#38485d',
        'inverse-primary': '#bec6e0',
        'surface-variant': '#e4e2e4',
        'on-primary-fixed': '#131b2e',
        'on-primary': '#ffffff',
        secondary: '#006a61',
        'surface-container-low': '#f6f3f5',
        error: '#ba1a1a',
        'primary-fixed-dim': '#bec6e0',
        'outline-variant': '#c6c6cd',
        'inverse-on-surface': '#f3f0f2',
        'error-container': '#ffdad6',
        'surface-container': '#f0edef',
        surface: '#fcf8fa',
        outline: '#76777d',
        'on-secondary-fixed-variant': '#005049',
        'surface-bright': '#fcf8fa',
        'on-tertiary-container': '#75859d',
        'surface-container-highest': '#e4e2e4',
        'secondary-fixed': '#89f5e7',
        tertiary: '#000000',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#6bd8cb',
        'on-background': '#1b1b1d',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        'stack-gap': '16px',
        'container-padding': '24px',
        gutter: '12px',
        'section-margin': '32px',
      },
      fontFamily: {
        'headline-md': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
        'label-sm': ['Work Sans', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'display-xl': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'label-xs': ['Work Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-xs': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
} satisfies Config
